// Comprehensive Personalized Career Dataset for Mumbai Candidate (Age 23)
// Evaluates 16 Career Pathways across Computer Science, High-Moat Hybrids, and Non-CS Sectors
// Derived from 75-Question Diagnostic Profile

const CANDIDATE_PROFILE = {
  name: "Candidate Profile (Confidential)",
  age: 23,
  location: "Mumbai, Maharashtra, India",
  education: "Pursuing Online B.Sc/B.Tech in Computer Science (Graduating 2028)",
  currentStack: "Unity with C# (2 Years Learning Experience, Mid-Level Logic, Multiplayer / PurrNet)",
  mathFoundation: "Strong (High School + College Calculus, Linear Algebra, Statistics)",
  hardwareSpecs: "Intel Core i7 13th Gen, NVIDIA RTX 4070 Laptop GPU, 16GB RAM + Owns VR Headset",
  droneProficiency: "Flight Simulator Experience (Joystick & Spatial Navigation Ready)",
  bandwidth: "10 - 20 Hours / Week Dedicated Learning",
  targetTimeline: "12 to 24 Months (Job Ready by late 2026 / 2027)",
  targetSalary: "₹6.0 – ₹12.0 LPA (₹50,000 – ₹1,00,000 / month starting)",
  primaryConcerns: [
    "AI automating conventional programming & gameplay coding",
    "Family priority: Long-term career stability & proven local Mumbai employment",
    "Aversion to public speaking, teaching, and cold client sales pitches",
    "Desire to leverage AI tools as accelerators rather than being replaced by them"
  ]
};

const CAREER_DATA = [
  // ================= TIER 1: PRIME STRATEGIC MATCHES (HIGHEST PERSONAL FIT + 6-12 LPA) =================
  {
    id: "enterprise-xr-sim",
    title: "Enterprise VR / XR Simulation Developer",
    tier: "Tier 1: Prime Match",
    fitScore: 96,
    category: "cs-adjacent",
    domain: "Spatial Computing & Defense/Industrial Sim",
    tag: "Top Recommendation",
    aiRisk: 16,
    aiRiskLabel: "Very Low Risk",
    transitionMonths: 7, // with 15h/week
    compMinLPA: 7.5,
    compMaxLPA: 14.0,
    compMedianLPA: 9.5,
    compDisplay: "₹7.5L - ₹14.0L LPA",
    gameDevOverlap: 95,
    humanMoat: "Headset hardware ergonomics, spatial boundary safety, physical motor coordination, and custom industrial hardware peripherals that LLMs cannot physically test or calibrate.",
    summary: "Build high-fidelity VR training simulators (aviation maintenance, high-voltage safety drills, defense operations) in Unity for Meta Quest/PC-VR headsets. Directly utilizes your RTX 4070 and VR headset without needing to create 3D art from scratch.",
    transferableSkills: [
      "2 years of Unity & C# component architecture",
      "Multiplayer state synchronization (PurrNet) for collaborative multi-user VR drills",
      "3D spatial vectors, quaternion rotations, and physics collision detection",
      "Direct hands-on access to a physical VR headset for hardware testing"
    ],
    skillGaps: [
      "Unity XR Interaction Toolkit (XRI) & OpenXR standards",
      "VR performance optimization (maintaining solid 72/90 FPS with zero motion sickness)",
      "Importing and optimizing pre-made industrial CAD models (reducing draw calls)"
    ],
    targetIndustriesMumbai: [
      "Tata Elxsi (Industrial XR Division)",
      "L&T Technology Services (Virtual Training Lab)",
      "Defense & Aerospace Contractors (Naval Dockyard / DRDO vendors in Mumbai)",
      "Mahindra & Mahindra Virtual Prototyping Studios"
    ],
    roadmapMonths: "Months 1-6",
    actionPlan: [
      "Month 1: Connect your VR headset to Unity via Quest Link and master the XR Interaction Toolkit.",
      "Month 2-3: Build a 'High-Voltage Electrical Substation Safety Simulator' using free asset store machinery.",
      "Month 4-5: Add 2-player multiplayer networking with PurrNet so two users can perform a collaborative inspection drill.",
      "Month 6: Record high-quality first-person video walkthroughs and publish an interactive GitHub/itch.io portfolio."
    ],
    familyProofPoint: "Leverages the ₹1.5L+ RTX 4070 and VR headset you already own into a prestigious corporate training field paying ₹8-12 LPA in Mumbai, immune to web-developer AI layoffs."
  },
  {
    id: "industrial-digital-twins",
    title: "Industrial Digital Twin & 3D Geospatial Engineer",
    tier: "Tier 1: Prime Match",
    fitScore: 92,
    category: "cs-adjacent",
    domain: "Smart Infrastructure & Port Logistics",
    tag: "High Value",
    aiRisk: 19,
    aiRiskLabel: "Very Low Risk",
    transitionMonths: 8,
    compMinLPA: 7.0,
    compMaxLPA: 13.5,
    compMedianLPA: 9.0,
    compDisplay: "₹7.0L - ₹13.5L LPA",
    gameDevOverlap: 90,
    humanMoat: "Real-world infrastructure integration, sensor coordinate transforms, factory telemetry ingestion, and brownfield industrial compliance that cannot be generated in a text prompt.",
    summary: "Develop interactive 3D virtual representations of real-world factories, warehouse logistics hubs, and ports (e.g., JNPT logistics) in Unity, connecting live data feeds to 3D facility models.",
    transferableSkills: [
      "Unity C# scripting and real-time 3D camera navigation",
      "Experience parsing multiplayer network packets (applies directly to IoT data feeds)",
      "Strong mathematical coordinate handling (Cartesian to GPS transforms)"
    ],
    skillGaps: [
      "Connecting Unity to live MQTT / REST sensor feeds (temperature, conveyor speeds)",
      "Cesium for Unity (real-world GIS satellite terrain integration)",
      "High-polygon CAD model decimation"
    ],
    targetIndustriesMumbai: [
      "JNPT & Navi Mumbai Port Logistics Automation",
      "Reliance Jio Smart City & Infrastructure Labs (Navi Mumbai)",
      "Adani Ports & Logistics Tech",
      "Siemens Industrial Software India"
    ],
    roadmapMonths: "Months 4-10",
    actionPlan: [
      "Month 4: Integrate Cesium for Unity to render high-resolution 3D Mumbai terrain.",
      "Month 5-6: Create an automated warehouse floor with moving autonomous forklifts driven by mock sensor scripts.",
      "Month 7-8: Build a dashboard overlay showing real-time machine uptime and heatmaps."
    ],
    familyProofPoint: "Aligns directly with India's massive infrastructure push (Smart Cities, Ports, Expressways) where government and corporate contractors pay top rates for 3D monitoring."
  },
  {
    id: "drone-photogrammetry-lead",
    title: "Commercial Drone Pilot & 3D Reality Capture Lead",
    tier: "Tier 1: Prime Match",
    fitScore: 89,
    category: "non-cs",
    domain: "Aviation & Physical Surveying",
    tag: "Physical Moat",
    aiRisk: 11,
    aiRiskLabel: "Immune to Pure AI",
    transitionMonths: 5,
    compMinLPA: 6.0,
    compMaxLPA: 11.0,
    compMedianLPA: 8.0,
    compDisplay: "₹6.0L - ₹11.0L LPA",
    gameDevOverlap: 75,
    humanMoat: "Mandatory physical DGCA license, physical drone piloting outdoors, regulatory aviation compliance, and site inspection liability that an AI model cannot legally or physically perform.",
    summary: "Acquire a government DGCA drone pilot certificate (takes 5-7 days training in Maharashtra), fly survey drones over infrastructure sites, and use your RTX 4070 to process aerial photos into 3D photogrammetry meshes via RealityCapture.",
    transferableSkills: [
      "Simulator flight experience (sticks, yaw/pitch/roll muscle memory)",
      "Spatial awareness and 3D coordinate geometry",
      "RTX 4070 GPU ready to run heavy photogrammetry reconstruction pipelines locally"
    ],
    skillGaps: [
      "DGCA Remote Pilot Certificate (RPC) from a certified flying school",
      "Photogrammetry software workflows (DJI Terra, RealityCapture, Pix4D)",
      "Airspace rules and DGCA Digital Sky compliance"
    ],
    targetIndustriesMumbai: [
      "Infrastructure & Highway Surveying (MSRDC, MMRDA projects)",
      "Solar & Renewable Energy Inspection (Tata Power Solar, Adani Green)",
      "Real Estate Aerial Mapping (Godrej Properties, Lodha)",
      "Private Surveying & Mining Consultancies"
    ],
    roadmapMonths: "Months 2-6",
    actionPlan: [
      "Month 2: Complete the 5-day DGCA Remote Pilot Certification at an approved institute near Mumbai/Pune.",
      "Month 3-4: Master RealityCapture on your RTX 4070 using open-source aerial survey datasets.",
      "Month 5: Export photorealistic 3D terrain into Unity to deliver interactive client inspection deliverables."
    ],
    familyProofPoint: "Comes with an official Government of India aviation license (DGCA), offering physical job permanence and zero risk of replacement by software algorithms."
  },
  {
    id: "data-engineering",
    title: "Data Platform & Automated Pipeline Engineer",
    tier: "Tier 1: Prime Match",
    fitScore: 88,
    category: "cs",
    domain: "Data Systems & Infrastructure",
    tag: "High Demand",
    aiRisk: 32,
    aiRiskLabel: "Moderate-Low Risk",
    transitionMonths: 8,
    compMinLPA: 7.5,
    compMaxLPA: 13.0,
    compMedianLPA: 9.5,
    compDisplay: "₹7.5L - ₹13.0L LPA",
    gameDevOverlap: 70,
    humanMoat: "Data integrity verification, complex distributed fault-tolerance, secure access governance, and preventing catastrophic data corruption across legacy corporate systems.",
    summary: "Move beyond basic dashboard charts into the automated data plumbing: writing automated ETL pipelines that reliably extract, validate, and store millions of records into SQL databases for Mumbai corporate firms.",
    transferableSkills: [
      "C# data structures, serialization, and memory buffer logic",
      "Multiplayer telemetry tracking and packet structure thinking",
      "College-level statistics and analytical reasoning"
    ],
    skillGaps: [
      "Advanced SQL (window functions, indexing, execution plan optimization)",
      "Python data pipelines (Pandas, PySpark, DuckDB)",
      "Automated orchestration tools (Airflow, dbt)"
    ],
    targetIndustriesMumbai: [
      "Financial Services & Fintech (HDFC Bank Tech, Axis Bank, Razorpay Mumbai)",
      "Big 4 & Consultancies (Deloitte, EY, PwC Mumbai tech centers)",
      "Retail & E-Commerce Logistics (Reliance Retail Digital, Nykaa)"
    ],
    roadmapMonths: "Months 4-11",
    actionPlan: [
      "Month 4-5: Master advanced PostgreSQL and SQL query optimization via online platforms.",
      "Month 6-7: Build automated Python ingestion pipelines fetching public financial and transport APIs.",
      "Month 8: Set up a local data warehouse in DuckDB/PostgreSQL processing 1,000,000+ records in seconds."
    ],
    familyProofPoint: "Data Engineering is one of the highest-paid corporate IT disciplines in Mumbai, with salaries growing rapidly from ₹8LPA to ₹20LPA+ within 3–4 years."
  },

  // ================= TIER 2: VIABLE CONTENDERS & STEPPING STONES =================
  {
    id: "software-game-qa",
    title: "Software & Game QA / Automation Test Engineer",
    tier: "Tier 2: Fast Gateway",
    fitScore: 82,
    category: "cs",
    domain: "Quality Assurance & Systems Testing",
    tag: "Accessible Entry",
    aiRisk: 38,
    aiRiskLabel: "Moderate Risk",
    transitionMonths: 4,
    compMinLPA: 5.5,
    compMaxLPA: 9.0,
    compMedianLPA: 6.8,
    compDisplay: "₹5.5L - ₹9.0L LPA",
    gameDevOverlap: 85,
    humanMoat: "Edge-case intuition, reproducing non-deterministic network race conditions, and user experience validation that scripted unit tests miss.",
    summary: "Systematically test interactive software and games, document glitches in Jira, and write C#/Python test automation scripts. Highly accessible immediate entry into Mumbai tech firms.",
    transferableSkills: ["Unity engine familiarity", "Bug diagnosis and reproducing game crashes", "Understanding multiplayer desync glitches"],
    skillGaps: ["Formal QA test case documentation", "Postman / API testing", "Automated UI testing frameworks"],
    targetIndustriesMumbai: ["Ubisoft Mumbai", "Jio Games", "Nazara Technologies", "FinTech Testing Firms"],
    roadmapMonths: "Months 1-4",
    actionPlan: ["Learn test case writing on TestRail", "Master Jira issue tracking", "Build an automated C# test suite for a Unity project"],
    familyProofPoint: "Fastest route to your first salaried corporate paycheck in Mumbai (within 4-6 months) while continuing your degree."
  },
  {
    id: "cctv-physical-security",
    title: "IP Video Surveillance & Physical Access Systems Tech",
    tier: "Tier 2: Physical Moat",
    fitScore: 80,
    category: "non-cs",
    domain: "Physical Security & Network Tech",
    tag: "Hands-on Moat",
    aiRisk: 14,
    aiRiskLabel: "Immune to Pure AI",
    transitionMonths: 4,
    compMinLPA: 5.0,
    compMaxLPA: 8.5,
    compMedianLPA: 6.5,
    compDisplay: "₹5.0L - ₹8.5L LPA",
    gameDevOverlap: 50,
    humanMoat: "Physical hardware installation, on-site cable testing, field camera angle adjustment, and physical facility security authorization.",
    summary: "Configure commercial IP security cameras, NVR recording servers, PoE switches, and biometric access control systems for corporate offices and housing societies in Mumbai.",
    transferableSkills: ["Basic networking (IP addresses, subnets, ports)", "Methodical troubleshooting", "Comfort configuring technical software"],
    skillGaps: ["Hikvision / Dahua / Cisco security hardware configuration", "PoE cabling and bandwidth calculation", "Physical access control protocols (Wiegand/OSDP)"],
    targetIndustriesMumbai: ["Godrej Security Solutions", "Honeywell Building Technologies", "Commercial IT Parks (Nesco, Mindspace, BKC)"],
    roadmapMonths: "Months 2-5",
    actionPlan: ["Take an online IP Surveillance & Networking short course", "Set up an IP camera and NVR system on a local switch", "Get certified in commercial security hardware"],
    familyProofPoint: "100% grounded in real-world physical equipment—no software AI can climb a ladder or route physical security cables."
  },
  {
    id: "ecommerce-catalog-ops",
    title: "E-Commerce Store & Marketplace Catalog Manager",
    tier: "Tier 2: Business Adjacent",
    fitScore: 78,
    category: "non-cs",
    domain: "Digital Retail & Merchant Operations",
    tag: "Practical Business",
    aiRisk: 35,
    aiRiskLabel: "Moderate Risk",
    transitionMonths: 3,
    compMinLPA: 5.0,
    compMaxLPA: 8.0,
    compMedianLPA: 6.2,
    compDisplay: "₹5.0L - ₹8.0L LPA",
    gameDevOverlap: 40,
    humanMoat: "Supplier relationship coordination, physical product return disputes, localized packaging compliance, and brand-specific merchandising judgment.",
    summary: "Manage product listings, pricing updates, inventory stockout alerts, and sales performance reports on Amazon India, Flipkart, and Shopify merchant panels.",
    transferableSkills: ["Comfort with computer software", "Logical categorization", "Ability to leverage AI for rapid product description writing"],
    skillGaps: ["Amazon Seller Central / Flipkart Seller Hub workflows", "Advanced Excel (VLOOKUP, Pivot Tables)", "Inventory stock replenishment formulas"],
    targetIndustriesMumbai: ["D2C Brands in Mumbai", "Retail Agencies", "FMCG Distributors"],
    roadmapMonths: "Months 1-3",
    actionPlan: ["Complete Amazon Seller University tutorials", "Master Excel inventory tracking sheets", "Manage or audit a real seller catalog"],
    familyProofPoint: "Very fast to learn with steady entry-level employment across hundreds of commercial consumer businesses in Mumbai."
  },
  {
    id: "realestate-valuation-analyst",
    title: "Commercial Real Estate Valuation & Leasing Analyst",
    tier: "Tier 2: Real Asset Moat",
    fitScore: 76,
    category: "non-cs",
    domain: "Commercial Real Estate & Property Assets",
    tag: "High Wealth Sector",
    aiRisk: 22,
    aiRiskLabel: "Low Risk",
    transitionMonths: 6,
    compMinLPA: 6.0,
    compMaxLPA: 10.5,
    compMedianLPA: 7.8,
    compDisplay: "₹6.0L - ₹10.5L LPA",
    gameDevOverlap: 45,
    humanMoat: "Local municipal zoning laws, in-person building inspections, neighborhood market intelligence, and physical lease negotiation.",
    summary: "Analyze property prices per square foot, calculate rental yield ratios, inspect commercial real estate units, and prepare property evaluation reports for developers and corporate tenants in Mumbai.",
    transferableSkills: ["Mathematical ratio calculation", "Structured analytical thinking", "Spatial comprehension of floorplans"],
    skillGaps: ["Mumbai real estate micro-market pricing trends (BKC, Lower Parel, Andheri, Navi Mumbai)", "Lease agreement structures (stamp duty, lock-in, escalation clauses)", "Financial yield modeling in Excel"],
    targetIndustriesMumbai: ["JLL India (Mumbai Office)", "CBRE South Asia", "Knight Frank India", "Colliers International"],
    roadmapMonths: "Months 3-8",
    actionPlan: ["Study Mumbai commercial real estate quarterly market reports", "Build an Excel model calculating IRR and capitalization rates for office leases", "Apply for junior research analyst roles at commercial brokerages"],
    familyProofPoint: "Real estate is Mumbai's premier wealth generator; valuation analysts build direct relationships with property developers and corporate investors."
  },
  {
    id: "smart-agriculture-hydroponics",
    title: "Smart Agriculture & Hydroponic Farm Operations",
    tier: "Tier 2: Physical Moat",
    fitScore: 79,
    category: "non-cs",
    domain: "AgTech & Controlled Environment Agriculture",
    tag: "Physical Moat",
    aiRisk: 10,
    aiRiskLabel: "Immune to Pure AI",
    transitionMonths: 6,
    compMinLPA: 5.5,
    compMaxLPA: 9.5,
    compMedianLPA: 7.2,
    compDisplay: "₹5.5L - ₹9.5L LPA",
    gameDevOverlap: 40,
    humanMoat: "Physical plant biology, sensor calibration (EC, pH, temperature), water circulation plumbing, and pest control that an AI model cannot physically touch or inspect.",
    summary: "Manage controlled environment agriculture (CEA) and commercial hydroponic farms supplying premium produce to Mumbai restaurants and supermarkets. Oversees automated nutrient dosing, climate sensors, and harvest cycles.",
    transferableSkills: ["Sensor data monitoring", "Methodical system calibration", "Systems logic (inputs -> growth rates -> yields)"],
    skillGaps: ["Plant biology & nutrient chemistry (N-P-K ratios, pH/EC meters)", "Hydroponic system plumbing (NFT, Dutch buckets, DWC)", "Farm operating costs and supply agreements"],
    targetIndustriesMumbai: ["Urban Kissan / Barton Breeze partners in Maharashtra", "Hydroponic farm setups in Karjat/Nashik/Pune", "Organic farm cooperatives supplying Mumbai retail"],
    roadmapMonths: "Months 2-6",
    actionPlan: [
      "Take an online/offline hands-on hydroponics masterclass near Mumbai",
      "Build a small pilot NFT hydroponic unit at home for leafy greens",
      "Intern or assist at a commercial greenhouse farm outside Mumbai"
    ],
    familyProofPoint: "Food and agriculture are fundamental human essentials; smart hydroponic operations represent the high-tech future of sustainable farming with zero AI layoff risk."
  },
  {
    id: "independent-market-trader",
    title: "Independent Financial Trader (Equities & Derivatives)",
    tier: "Tier 2: High Leverage",
    fitScore: 75,
    category: "non-cs",
    domain: "Capital Markets & Technical Trading",
    tag: "High Independence",
    aiRisk: 25,
    aiRiskLabel: "Low Risk",
    transitionMonths: 10,
    compMinLPA: 6.0,
    compMaxLPA: 20.0,
    compMedianLPA: 10.0,
    compDisplay: "₹6.0L - ₹20.0L+ (Performance Based)",
    gameDevOverlap: 65,
    humanMoat: "Human risk appetite, emotional discipline, real-time capital preservation under uncertainty, and personal financial skin-in-the-game.",
    summary: "Trade equities, index options (Nifty/BankNifty), and commodities independently using technical price action, statistical risk management, and order flow analysis without boss or clients.",
    transferableSkills: ["Mathematical probability and expected value calculation", "Pattern recognition on charts", "Familiarity with screen-based software and automated execution"],
    skillGaps: ["Emotional discipline and psychological loss tolerance", "Strict risk-to-reward position sizing rules", "Capital requirement (needs risk capital to trade)"],
    targetIndustriesMumbai: ["Dalal Street Proprietary Desks", "Independent Trading (Solo Home Office)", "Boutique Family Offices"],
    roadmapMonths: "Months 4-12",
    actionPlan: [
      "Master price action and risk management on paper trading accounts (TradingView / Sensibull)",
      "Backtest a defined strategy on 2 years of Nifty historical data",
      "Trade with micro-capital (₹25k) strictly adhering to 1% max risk per trade"
    ],
    familyProofPoint: "Total independence (no boss, no clients, no public speaking), but requires strict emotional discipline and proof of profitability before committing real family savings."
  },
  {
    id: "culinary-cloud-kitchen-ops",
    title: "Culinary Arts & Cloud Kitchen Brand Operations",
    tier: "Tier 2: Real World Craft",
    fitScore: 72,
    category: "non-cs",
    domain: "Food & Beverage (F&B) and Cloud Kitchens",
    tag: "Zero AI Threat",
    aiRisk: 8,
    aiRiskLabel: "Completely Immune",
    transitionMonths: 6,
    compMinLPA: 5.0,
    compMaxLPA: 9.0,
    compMedianLPA: 6.5,
    compDisplay: "₹5.0L - ₹9.0L LPA",
    gameDevOverlap: 35,
    humanMoat: "Human taste, olfactory sensory evaluation, physical knife work, cooking temperatures, and food safety hygiene that AI cannot replicate.",
    summary: "Run commercial kitchen operations or delivery-only cloud kitchen brands in Mumbai: managing recipe standard operating procedures (SOPs), kitchen staff, food ingredient procurement, and Swiggy/Zomato brand metrics.",
    transferableSkills: ["Process iteration (recipes as algorithms)", "Precise measurement and timing", "Menu optimization using ordering data"],
    skillGaps: ["Commercial culinary techniques & food hygiene (FSSAI regulations)", "Food cost percentage modeling (controlling raw material waste)", "Kitchen line workflow & equipment maintenance"],
    targetIndustriesMumbai: ["Rebel Foods (Faasos, Behrouz Biryani Mumbai HQ)", "Curefoods / Kitchens@ Mumbai", "Independent Boutique Cloud Kitchens in Bandra/Andheri"],
    roadmapMonths: "Months 2-6",
    actionPlan: [
      "Complete an FSSAI Food Safety certification",
      "Design standardized 5-item cloud kitchen menu with exact ingredient costings in Excel",
      "Work as a kitchen/operations supervisor at an established food delivery brand"
    ],
    familyProofPoint: "Food is an eternal physical necessity in Mumbai; people will always eat, and no AI algorithm can cook physical food or replace human taste."
  },

  // ================= TIER 3: EVALUATED ALTERNATIVES (INCLUDED FOR FULL TRANSPARENCY) =================
  {
    id: "quant-finance-analyst",
    title: "Quantitative Systems & Risk Modeler",
    tier: "Tier 3: Evaluated",
    fitScore: 71,
    category: "non-cs",
    domain: "High Finance & Capital Markets",
    tag: "High Barrier",
    aiRisk: 26,
    aiRiskLabel: "Low-Mod Risk",
    transitionMonths: 14,
    compMinLPA: 12.0,
    compMaxLPA: 25.0,
    compMedianLPA: 16.0,
    compDisplay: "₹12.0L - ₹25.0L LPA",
    gameDevOverlap: 70,
    humanMoat: "Fiduciary liability, systemic market stress testing, and legal responsibility for massive capital allocations.",
    summary: "Apply statistics and simulation models to forecast financial risks and backtest algorithmic trading systems in Mumbai's financial district.",
    transferableSkills: ["Strong college-level math (calculus, linear algebra, probability)", "Simulation architecture", "Fast computational logic"],
    skillGaps: ["Deep financial econometrics", "Stochastic calculus & derivatives pricing", "High barrier: strong preference for IIT/ISI/IIM degrees in initial screening"],
    targetIndustriesMumbai: ["Dalal Street Brokerages", "Proprietary Trading Desks (BKC)", "Investment Banks (Morgan Stanley, Nomura)"],
    roadmapMonths: "Months 8-18",
    actionPlan: ["Study financial mathematics and option Greeks", "Build backtesting scripts in Python using historical NSE tick data"],
    familyProofPoint: "Pays the highest salaries in Mumbai, but has an intense academic screening filter that makes immediate 1-year entry harder without a tier-1 finance degree."
  },
  {
    id: "import-export-ops",
    title: "Customs & Freight Forwarding Operations Executive",
    tier: "Tier 3: Evaluated",
    fitScore: 68,
    category: "non-cs",
    domain: "International Trade & Port Logistics",
    tag: "Physical Trade",
    aiRisk: 24,
    aiRiskLabel: "Low Risk",
    transitionMonths: 6,
    compMinLPA: 4.5,
    compMaxLPA: 7.5,
    compMedianLPA: 5.8,
    compDisplay: "₹4.5L - ₹7.5L LPA",
    gameDevOverlap: 30,
    humanMoat: "Physical port customs inspections, government tariff disputes, shipping container physical handover, and maritime port authority coordination.",
    summary: "Coordinate international container shipments arriving at JNPT port: handling shipping bills of entry, customs tariff codes, shipping line bookings, and port clearance.",
    transferableSkills: ["Attention to detail", "Methodical document verification"],
    skillGaps: ["Customs EDI systems & ICEGATE portal filing", "Harmonized System (HS) tariff classification", "Maritime shipping documents (Bill of Lading, Letter of Credit)"],
    targetIndustriesMumbai: ["JNPT / Nhava Sheva Freight Forwarders", "Shipping Agencies (Fort / Ballard Estate Mumbai)", "Container Freight Stations (CFS)"],
    roadmapMonths: "Months 3-7",
    actionPlan: ["Take an Indian Institute of Freight Forwarders (IIFF) certification", "Learn customs documentation filing on ICEGATE"],
    familyProofPoint: "Anchored in Mumbai's historic shipping ports with steady demand, though starting pay (₹4.5–6 LPA) is lower than specialized 3D simulation."
  },
  {
    id: "enterprise-csharp-backend",
    title: "Enterprise C# and .NET Core Backend Engineer",
    tier: "Tier 3: Evaluated",
    fitScore: 62,
    category: "cs",
    domain: "Corporate Enterprise Banking Software",
    tag: "User Dislikes CRUD",
    aiRisk: 42,
    aiRiskLabel: "Moderate Risk",
    transitionMonths: 6,
    compMinLPA: 6.5,
    compMaxLPA: 12.0,
    compMedianLPA: 8.5,
    compDisplay: "₹6.5L - ₹12.0L LPA",
    gameDevOverlap: 80,
    humanMoat: "Legacy enterprise banking database integration, compliance audits, and high-concurrency transactional consistency.",
    summary: "Write ASP.NET Core APIs and backend services for banks and insurance companies in Mumbai. High C# code overlap, but involves repetitive business CRUD logic.",
    transferableSkills: ["2 years of C# syntax and object-oriented design", "Multi-threaded async programming"],
    skillGaps: ["ASP.NET Core Web API frameworks", "Entity Framework Core & SQL Server", "Enterprise microservices architecture"],
    targetIndustriesMumbai: ["Barclays Mumbai", "Morgan Stanley IT", "Tata Consultancy Services (TCS)"],
    roadmapMonths: "Months 3-8",
    actionPlan: ["Build a RESTful microservice with ASP.NET Core and SQL Server"],
    familyProofPoint: "Massive corporate job volume in Mumbai, but directly conflicts with your preference against boring corporate business logic."
  },
  {
    id: "web-fullstack-dev",
    title: "Web & Full-Stack Application Developer",
    tier: "Tier 3: Evaluated",
    fitScore: 40,
    category: "cs",
    domain: "Web & SaaS Development",
    tag: "High AI Risk",
    aiRisk: 76,
    aiRiskLabel: "High Vulnerability",
    transitionMonths: 9,
    compMinLPA: 4.5,
    compMaxLPA: 9.0,
    compMedianLPA: 6.5,
    compDisplay: "₹4.5L - ₹9.0L LPA",
    gameDevOverlap: 35,
    humanMoat: "Very weak moat; LLMs and autonomous coding agents can synthesize standard React/Node.js web pages, forms, and database backends in seconds.",
    summary: "Building standard websites, web dashboards, and mobile web frontends using JavaScript/React/Node.js.",
    transferableSkills: ["Basic programming logic"],
    skillGaps: ["HTML, CSS, JavaScript, React, Node.js from scratch"],
    targetIndustriesMumbai: ["Web design agencies", "Early-stage consumer startups"],
    roadmapMonths: "Not Recommended",
    actionPlan: ["Avoid pivoting into general web development due to high AI automation risk."],
    familyProofPoint: "Exactly the sector being commoditized most aggressively by AI coding tools; your skepticism here was 100% justified."
  },
  {
    id: "cybersecurity-analyst",
    title: "SOC Cybersecurity & Network Security Analyst",
    tier: "Tier 3: Evaluated",
    fitScore: 55,
    category: "cs",
    domain: "Information Security & Monitoring",
    tag: "Steep Learning Curve",
    aiRisk: 24,
    aiRiskLabel: "Low Risk",
    transitionMonths: 11,
    compMinLPA: 6.0,
    compMaxLPA: 11.0,
    compMedianLPA: 8.0,
    compDisplay: "₹6.0L - ₹11.0L LPA",
    gameDevOverlap: 40,
    humanMoat: "Adversarial threat hunting, legal data breach compliance, and real-time incident containment.",
    summary: "Monitor security information events (SIEM), detect intrusion attempts, and investigate firewall alerts for corporate banks and data centers.",
    transferableSkills: ["Systematic analytical mindset"],
    skillGaps: ["Linux system administration", "TCP/IP networking fundamentals", "Security certs (CompTIA Security+, CEH)"],
    targetIndustriesMumbai: ["Bank SOC centers in Mumbai", "Managed Security Providers"],
    roadmapMonths: "Months 6-14",
    actionPlan: ["Pass CompTIA Security+ and study Wireshark network packet analysis"],
    familyProofPoint: "Great moat, but requires building full IT networking foundations from ground zero compared to leveraging your existing Unity/C# base."
  },
  {
    id: "game-systems-designer",
    title: "Game Systems & Combat Mechanics Designer",
    tier: "Tier 3: Evaluated",
    fitScore: 48,
    category: "cs-adjacent",
    domain: "Game Mechanics & Entertainment",
    tag: "User Marked Boring",
    aiRisk: 45,
    aiRiskLabel: "Moderate Risk",
    transitionMonths: 6,
    compMinLPA: 4.5,
    compMaxLPA: 8.0,
    compMedianLPA: 6.0,
    compDisplay: "₹4.5L - ₹8.0L LPA",
    gameDevOverlap: 85,
    humanMoat: "Human fun factor, player psychology, and intuition on gameplay feel.",
    summary: "Tuning character controllers, jumping physics, level pacing, and combat encounters inside Unity.",
    transferableSkills: ["Unity editor and C# scripting"],
    skillGaps: ["Formal game design documentation", "Player psychology metrics"],
    targetIndustriesMumbai: ["Local mobile game studios", "Indie publishers"],
    roadmapMonths: "Months 2-6",
    actionPlan: ["Excluded based on diagnostic preference (user finds level/combat tuning boring)."],
    familyProofPoint: "Subject to gaming industry hiring freezes and lower entry-level compensation in India compared to enterprise simulation."
  },
  {
    id: "film-vfx-matchmove",
    title: "Film VFX & 3D Camera Tracking Artist",
    tier: "Tier 3: Evaluated",
    fitScore: 42,
    category: "non-cs",
    domain: "Film & Entertainment Media",
    tag: "User Aversion to Film",
    aiRisk: 28,
    aiRiskLabel: "Low-Mod Risk",
    transitionMonths: 8,
    compMinLPA: 4.0,
    compMaxLPA: 7.5,
    compMedianLPA: 5.5,
    compDisplay: "₹4.0L - ₹7.5L LPA",
    gameDevOverlap: 65,
    humanMoat: "Physical live-action camera matching, lens distortion calibration, and live film director coordination.",
    summary: "Reconstruct 3D camera motions from live film footage for Bollywood/Hollywood VFX studios in Goregaon/Andheri.",
    transferableSkills: ["3D coordinate systems and perspective cameras"],
    skillGaps: ["3DEqualizer software", "Film studio crunch culture"],
    targetIndustriesMumbai: ["DNEG Mumbai", "Prime Focus", "Redchillies VFX"],
    roadmapMonths: "Not Recommended",
    actionPlan: ["Excluded based on diagnostic preference (user dislikes film industry)."],
    familyProofPoint: "Lower entry pay (₹4–5 LPA) with notorious overtime crunches; enterprise simulation offers far better work-life balance."
  },
  {
    id: "public-sector-banking",
    title: "Public Sector Bank Officer (SBI PO / RBI Grade B)",
    tier: "Tier 3: Evaluated",
    fitScore: 35,
    category: "non-cs",
    domain: "Government Banking & Public Sector",
    tag: "User Aversion to Govt Exams",
    aiRisk: 8,
    aiRiskLabel: "Completely Immune",
    transitionMonths: 18,
    compMinLPA: 8.5,
    compMaxLPA: 16.0,
    compMedianLPA: 11.5,
    compDisplay: "₹8.5L - ₹16.0L LPA (plus Govt Quarters/Benefits)",
    gameDevOverlap: 25,
    humanMoat: "Sovereign government employment, statutory legal authority, zero layoff risk.",
    summary: "Government bank probationary officer managing branch operations, loans, and regulatory oversight.",
    transferableSkills: ["Strong quantitative math and logical aptitude"],
    skillGaps: ["General banking awareness, Indian economy, UPSC/IBPS competitive exam preparation"],
    targetIndustriesMumbai: ["State Bank of India (Bandra)", "Reserve Bank of India (Fort/BKC)"],
    roadmapMonths: "Months 12-24",
    actionPlan: ["Excluded based on diagnostic preference (user not interested in public sector bureaucracy)."],
    familyProofPoint: "Unbeatable stability, but requires 1-2 years of full-time exam cramming with sub-1% selection ratios."
  }
];

// High-level Macro Comparison Trends
const MACRO_ANALYSIS = {
  mumbaiMarketOutlook: "Mumbai is experiencing an unprecedented surge in industrial XR simulation, port logistics automation (JNPT/Navi Mumbai), and infrastructure digital twins, offering starting packages of ₹7.5 - ₹12 LPA.",
  strategicVerdict: "Do NOT discard your 2 years of Unity & C# experience! By redirecting your Unity skills from consumer games into Enterprise VR Training Simulators, Industrial Digital Twins, and Drone Photogrammetry, you immediately bypass the AI coding collapse and secure high-paying, stable local Mumbai corporate employment.",
  keyAdvantages: [
    { title: "RTX 4070 Laptop GPU + VR Headset", desc: "You already own the exact high-end hardware required for Enterprise XR and RealityCapture, eliminating a ₹2,00,000+ setup barrier." },
    { title: "Unity + C# Base (2 Years)", desc: "You have 80-95% direct skill transfer into Enterprise VR Simulation and Digital Twins, saving 12+ months of learning time." },
    { title: "Math Foundation", desc: "Comfort with vectors, calculus, and statistics gives you an innate edge in spatial kinematics and data engineering." },
    { title: "AI-Augmented Developer", desc: "Because you actively use AI to generate code patterns, you will build enterprise simulation prototypes 3x faster than traditional slow developers." }
  ]
};

// Skill Taxonomy Overlap Data (Personalized Radar)
const CANDIDATE_RADAR_DATA = {
  labels: [
    "Unity & C# Logic",
    "3D Math & Spatial Vectors",
    "VR Headset & Hardware",
    "Data & Pipeline Logic",
    "Physical World Moat",
    "AI Leverage Factor"
  ],
  datasets: [
    {
      label: "Your Current Profile",
      data: [85, 80, 75, 60, 65, 90],
      borderColor: "#3b82f6",
      backgroundColor: "rgba(59, 130, 246, 0.2)",
      borderWidth: 2
    },
    {
      label: "Enterprise VR / XR Developer",
      data: [92, 85, 95, 60, 85, 88],
      borderColor: "#10b981",
      backgroundColor: "rgba(16, 185, 129, 0.15)",
      borderWidth: 2
    },
    {
      label: "Drone & Reality Capture Lead",
      data: [45, 75, 40, 55, 98, 70],
      borderColor: "#f59e0b",
      backgroundColor: "rgba(245, 158, 11, 0.15)",
      borderWidth: 2
    },
    {
      label: "Data Platform Engineer",
      data: [70, 70, 20, 95, 50, 85],
      borderColor: "#8b5cf6",
      backgroundColor: "rgba(139, 92, 246, 0.15)",
      borderWidth: 2
    }
  ]
};
